### PR TITLE
Metadata detail & forms.py update

### PR DESCRIPTION
**Pull request by ErikKBethke**
Remove truncation of abstract in metadata detail page, add hazard information in metadata detail, capitalize labels & fix 1 label.

### CODE REVIEW

**Comment by ErikKBethke** [comment]
@stufraser1 If there are no conflicts, this should resolve a few issues that are open and also some things we discussed on 10/4/17

**Comment by stufraser1** [comment]
@Vampouille  can this be reviewed and merged please?

**Comment by stufraser1** [comment]
@fjacon @Vampouille  Please can you arrange for this to be reviewed and merged? Thank you

**Comment by fjacon** [comment]
@stufraser1 sure, I will plan this for next week.

**Comment by Vampouille** [comment]
@ErikKBethke in order to follow development of upstream geonode repo, I have setup some git branches. We have one branch for geonode without modification for gfdrr (c2c_geonode) and we have several commits to add modifications for gfdrr (mainly hazard types). Those commits are located at the end of `vx` branch where `x` is an integer. For example we have following tag : 
* https://github.com/GFDRR/geonode/tree/v1
* https://github.com/GFDRR/geonode/tree/v2
Your modifications seems to be related to modification dedicated to gfdrr, so, in order to merge your "patch" in current code of gfdrr. I need to append your commits to v2 branch and create a new v3 tag.

Can you confirm that none of your modifications should be include in main geonode code ?

**Comment by stufraser1** [comment]
@Vampouille 
None of the modifications should be include in main geonode code - please go ahead and make the changes on the Labs Geonode only.

**Comment by fjacon** [comment]
I will assign @pvalsecc  as he is taking over @Vampouille

**Pull request closed without merging**
